### ISSUE TITLE
Why is the supervision tree not startedon app start

### ISSUE THREAD

**Issue by phanimahesh** [joedevivo/chatterbox#126]
Is there any specific reason for not having a mod entry in app.src?

Without that, chatterbox:start() has to be manually called to strt the supervision tree.

**Comment by tsloughter** [comment]
It isn't really meant to be used. Best to use an acceptor pool, like https://github.com/fishcakez/acceptor_pool/ and having it under your own supervision tree. grpcbox is an example of using chatterbox this way, https://github.com/tsloughter/grpcbox/blob/master/src/grpcbox_acceptor.erl#L18

I have toyed with the idea of adding support directly for acceptor_pool, and preferably removing the ranch support, but I'm sure I'll have push back and will just leave that as is :)

But either way, with or without builtin use of acceptor_pool, it'll need to be started under your own supervisor.

`chatterbox:start()` should probably just be removed since all it does run `application:ensure_all_started(chatterbox)`
